### PR TITLE
removed latest recipe function

### LINKED ISSUE #21: latest recipe api endpoint is paid only
**Describe the bug**

the latest recipe button will not load any data as the api owner has made that endpoint paid only.

you need to support them via patreon in order to get access.

here is the link: https://www.patreon.com/thedatadb

**To Reproduce**
1. Go to the homepage
2. Click on latest
3. Scroll down to latest recipe
4. See error in console or by going to the endpoint in the web browser: https://www.themealdb.com/api/json/v1/1/latest.php

**Expected behavior**
the latest recipe will load.

**Screenshots**
not needed

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version: 77.0.3865.90

**Smartphone (please complete the following information):**
not tested on a smartphone.

**Additional context**
maybe you can contact them and get access as this is an open source project?

### PR DESCRIPTION
**Pull request by PaulLiamAG**
Removes all code related to the latest recipe function.

fixes #21

### CODE REVIEW

**Review by NitinNair89 — CHANGES_REQUESTED** [review]
Looks good. Do we need the check for type=r now as latest recipe is being removed?

**Comment by PaulLiamAG** [comment]
I think the check is still valid as the value can be "r" or "u" both are passed into the method. 
unless I'm reading it wrong :P

**Comment by NitinNair89** [comment]
> I think the check is still valid as the value can be "r" or "u" both are passed into the method.
> unless I'm reading it wrong :P

Ok, I haven't checked it thoroughly. LOL. If everything is functioning as expected then it's good.

Please pull the latest code, resolve conflicts and push your changes.

**Comment by PaulLiamAG** [comment]
Merged from master :)

**Review by NitinNair89 — APPROVED** [review]

**Pull request merged**
