### PR TITLE
Made NavBar responsive

### PR DESCRIPTION
**Pull request by thebhushanmhatre**
Made CSS file more readable which will make it easier to tinker,
Made NavBar responsive and removed some media queries which were useless and added some.
Also changed Go to Top button more awesome.
More changes coming up in future.
Thanks.

### CODE REVIEW

**Comment by thebhushanmhatre** [comment]
I forgot to add two lines(in app.css) which I will later.

**Review by NitinNair89 — CHANGES_REQUESTED** [review]
Please minify the CSS.

**Comment by NitinNair89** [comment]
Also please share the GitHub pages link for your forked repo so I can review the changes visually

**Comment by NitinNair89** [comment]
@thebhushanmhatre - Please see my above comments.

**Comment by thebhushanmhatre** [comment]
Hi @NitinNair89 ,
Minify CSS as in U want that old format as it was earlier ?
I would urge you to keep the format which i gave u, because that is the format most of the developers use so it will be easier for other developers to make changes faster.
If u still want me to revert to that old format, I will do it (After all it takes hardly 10 clicks to do it 👍)

[And here is the requested link](https://github.com/thebhushanmhatre/TheHungryRecipes/tree/issue-2)

**Comment by thebhushanmhatre** [comment]
Also if u want to see changes visually u can see above commits links/pr 
Copying and pasting the same below.

https://github.com/NitinNair89/TheHungryRecipes/pull/11/commits/c9bf4ef1408fa24eb2f4c20a5332c22d5b3deff8

https://github.com/NitinNair89/TheHungryRecipes/pull/11/commits/81493c3d4852ce055b3ee80342c98e139ff02b4e


https://github.com/NitinNair89/TheHungryRecipes/pull/11/commits/d48fc4514237ea1a5c7c1f754fb1a66ec648e33f


https://github.com/NitinNair89/TheHungryRecipes/pull/11/commits/97c220f5483d834fb46bd98826a46fcaaf99abdf

**Comment by NitinNair89** [comment]
Setup a GitHub page for your forked repo. I have already reviewed your code. For development, using expanded CSS is fine, but before moving to production, you should always minify CSS and JS resources  :)

**Comment by thebhushanmhatre** [comment]
I can't setup more than one Github page and i already have one. 
Attaching the Screenshots as alternate to see the result.
I will minify the CSS as requested.

image

image

image

**Comment by NitinNair89** [comment]
You can edit your fork repo's settings to have the GitHub page of the repo to point to your fork URL. :)

For the small screen, the image alignment is incorrect. It should always be placed on top of the random recipe button in all resolutions.

**Comment by thebhushanmhatre** [comment]
I have only made navbar responsive the rest of website is yet to be made responsive.
Accept the PR for only that.

I will making many other changes eventually (on holidays/weekend only)
I am not an expert in making websites responsive so it will take time.
I will be making multiple PRs one change at a time,
Request you to accept this on for time being.
Thanks.

**Comment by NitinNair89** [comment]
> I have only made navbar responsive the rest of website is yet to be made responsive.
> Accept the PR for only that.
> 
> I will making many other changes eventually (on holidays/weekend only)
> I am not an expert in making websites responsive so it will take time.
> I will be making multiple PRs one change at a time,
> Request you to accept this on for time being.
> Thanks.

That's fine. Take your time. You can use this PR for all your tested commits. The issue was to make the site responsive and not just the navbar. :)

Once everything looks good at the basic level, I will approve this PR. Good luck! :+1:

**Comment by thebhushanmhatre** [comment]
@NitinNair89 Can You please resolve the conflict.
And do merge the changes without closing the issue faster (This is sure to avoid merge conflicts, I think).
I can see u have added many new things on your website.
How do I get those changes on my local machine without deleting my changes?
Can "rebase" help ?
I think answer to this question will help me resolve future merge conflicts on my own.
Let me know if you have any idea. Or Google Zindabad :)
Thanks

**Comment by NitinNair89** [comment]
> @NitinNair89 Can You please resolve the conflict.
> And do merge the changes without closing the issue faster (This is sure to avoid merge conflicts, I think).
> I can see u have added many new things on your website.
> How do I get those changes on my local machine without deleting my changes?
> Can "rebase" help ?
> I think answer to this question will help me resolve future merge conflicts on my own.
> Let me know if you have any idea. Or Google Zindabad :)
> Thanks

Which IDE are you using? If it's a normal text editor like Sublime, the safest approach for you will be to backup your code. Then pull the latest code changes to your forked repo using git's fetch command (Google it). 

Once you have the latest code with you, manually type in your backup code making sure nothing is affected. Then commit and push your changes. :)

**Comment by thebhushanmhatre** [comment]
I use Sublime,
This helped https://gist.github.com/CristinaSolana/1885435
I using fetch but it was not working because i had not updated my forked copy (I guess).
Thanks.
Btw the new website looks good and i guess u still have to update the latest page right ?
I am having problem with keeping hat above random recipe can u look into it after I make changes?

**Comment by thebhushanmhatre** [comment]
Also, one Doubt:
why are u not combining the following 
`<div class="container">`
`  <div class="row">`
 `   <div class="twelve columns">`
`      <div class="row d-flex">`
into this
`<div class="container twelve columns row d-flex">`
This makes it difficult to add responsive styles
one tag overrides or limits another

**Comment by NitinNair89** [comment]
> Also, one Doubt:
> why are u not combining the following
> `<div class="container">`
> ` <div class="row">`
> ` <div class="twelve columns">`
> ` <div class="row d-flex">`
> into this
> `<div class="container twelve columns row d-flex">`
> This makes it difficult to add responsive styles
> one tag overrides or limits another

We cannot combine it. That's how the grid system works. You can read the documentation for Skeleton or Bootstrap. :slightly_smiling_face: 

Do not use the rebase command. Take backup of your code, use git fetch upstream to pull latest version. Then use git merge upstream/master to merge the changes.

For conflicting files you will see additional lines in your code, something like "<<head" followed by "===" that denotes the end of head. And another line like "master". So use it.

I suggest you use VS code IDE. It's really good. Or you can use gitpod.io to code in your browser.

**Review by NitinNair89 — CHANGES_REQUESTED** [review]
Waiting for conflict resolution

**Comment by thebhushanmhatre** [comment]
I will continue my work on weekends (holidays) if time permits.
I will take latest code at that time and make changes into them,
Deleting this branch and pull request since its of no use now.
Thanks and regards. 👍

**Comment by NitinNair89** [comment]
> I will continue my work on weekends (holidays) if time permits.
> I will take latest code at that time and make changes into them,
> Deleting this branch and pull request since its of no use now.
> Thanks and regards.

Ok

**Pull request closed without merging**
