### PR TITLE
Updated about section, added GitHub Shields

### PR DESCRIPTION
**Pull request by tobifroe**
The readme doesn't say much so I couldn't write too much, if you want anything else in there let me know!

### CODE REVIEW

**Comment by NitinNair89** [comment]
Please share screenshot of how the about section looks with your changes :slightly_smiling_face:

**Comment by tobifroe** [comment]
Bildschirmfoto 2019-10-21 um 18 01 40
Here you go :)

**Comment by NitinNair89** [comment]
> Bildschirmfoto 2019-10-21 um 18 01 40
> 
> Here you go :)

Looks cool! :+1:

**Comment by NitinNair89** [comment]
Maybe you can mention somewhere that project is open source and contributed by amazing people. You can remove the hyperlink to my profile :)

**Comment by tobifroe** [comment]
Bildschirmfoto 2019-10-21 um 18 37 00
How about this?

**Comment by NitinNair89** [comment]
> Bildschirmfoto 2019-10-21 um 18 37 00
> 
> How about this?

Looks good. How about an extra break before the "this project is open source..." sentence?

**Comment by tobifroe** [comment]
Bildschirmfoto 2019-10-22 um 09 24 14
Added that, I think we're good to go!

**Review by NitinNair89 — APPROVED** [review]

**Pull request merged**
