### PR TITLE
Update Recipe Category Navbar

### PR DESCRIPTION
**Pull request by saguins**
**Recipe Category Navbar (Update Version)**

**Full Preview**

image

**Close-up Preview**

image

### CODE REVIEW

**Review by NitinNair89 — CHANGES_REQUESTED** [review]
How does it look with these changes?

**Review by NitinNair89 — APPROVED** [review]

**Comment by saguins** [comment]
Thank you for all your suggestion to help me finish my Recipe Category Navbar pull request with better result. I have learned a lot from this repo. Thanks again. 🔥💪

**Comment by NitinNair89** [comment]
> How does it look with these changes?

@saguins please show screenshot :)

**Comment by NitinNair89** [comment]
> Thank you for all your suggestion to help me finish my Recipe Category Navbar pull request with better result. I have learned a lot from this repo. Thanks again.

The recipe category list was a wonderful addition to this project. I never thought of implementing it until you came up with your suggestion. It was wonderful. Happy to collaborate with you in future as well.:)

**Pull request merged**
