### PR TITLE
Fixed sticky Header when scrolling

### PR DESCRIPTION
**Pull request by RodolfoBrian**

### CODE REVIEW

**Review by NitinNair89 — CHANGES_REQUESTED** [review]
I have commented on the issue. Please make changes. Also don't change the overall colors of the website.

**Comment by NitinNair89** [comment]
Can you show latest screenshot with changes? :)

**Comment by RodolfoBrian** [comment]
thehungryrecipe

**Comment by NitinNair89** [comment]
It looks like it's getting cropped from the bottom. Can you refer some good navbar UI and update it please? There's more top padding in your screenshot. We need equal padding.

**Comment by RodolfoBrian** [comment]
thehungryrecipe

**Comment by NitinNair89** [comment]
> thehungryrecipe

The header is taking too much of space. A sleek and narrow header is preferred.

**Comment by RodolfoBrian** [comment]
thehungryrecipe

**Comment by RodolfoBrian** [comment]
> > thehungryrecipe
> 
> The header is taking too much of space. A sleek and narrow header is preferred.

#36 - could you tell me the requirements

**Pull request closed without merging**
