### PR TITLE
Make responsive

### LINKED ISSUE #2: Make the site responsive
**Enhancement:**
- Currently the website is not responsive and the UI breaks at many places

**What I want:**
- A good approach to making the website responsive and easily accessible to all screen sizes

---

**IF YOU WANT TO WORK ON THIS, PLEASE CLAIM IT BY COMMENTING BELOW**

### PR DESCRIPTION
**Pull request by michellelim**
Fixes https://github.com/NitinNair89/TheHungryRecipes/issues/2
Screen Shot 2019-10-17 at 9 05 42 PM

### CODE REVIEW

**Comment by NitinNair89** [comment]
> Fixes #2
> Screen Shot 2019-10-17 at 9 05 42 PM

Can you share screenshots for all breakpoints?

**Comment by NitinNair89** [comment]
@michellelim still working on this?

**Comment by michellelim** [comment]
it's complete

**Comment by NitinNair89** [comment]
> it's complete

Can you please share screenshot of all major breakpoints?

**Pull request closed without merging**
