### PR TITLE
Handle no recipe found notification

### LINKED ISSUE #25: no recipe available message
**Is your feature request related to a problem? Please describe.**
When you search for a keyword and it does not find any results it just scrolls you down to the last search without telling you it found no recipes. or if you have not searched before it does not do anything whatsoever.  

**Describe the solution you'd like**
I would like to add a message if no recipes are found so the user knows what's going on.
something on the lines of: "Hmm looks like we dont have any recipes for <keyword>, would you like to search again? <search button>"

**Describe alternatives you've considered**
I think showing a helpful message is the only option.

**Additional context**
try to search for "ko", it should take you down to the past search or do nothing if you have not searched before.

### PR DESCRIPTION
**Pull request by PaulLiamAG**
I have finally got around to implementing the code :)

I think it works well and is a lot better than having no feedback when no recipes are found. 

Feedback welcome

fixes #25

### CODE REVIEW

**Comment by NitinNair89** [comment]
Can you share screenshots?

**Comment by PaulLiamAG** [comment]
here is a screenshot:  https://www.dropbox.com/s/4v49izeqhdqh34s/Screenshot%202019-10-19%2016.11.27.png?dl=0

**Comment by NitinNair89** [comment]
Looks really good. Can you reduce the padding of the error box? And maybe increase the don't size a bit? Should we have a different color other than green since it is not a success message?

**Comment by PaulLiamAG** [comment]
do you think this is an improvement? https://www.dropbox.com/s/w9ttpgs5y9w1sro/Screenshot%202019-10-21%2015.36.17.png?dl=0

**Comment by NitinNair89** [comment]
> do you think this is an improvement? https://www.dropbox.com/s/w9ttpgs5y9w1sro/Screenshot%202019-10-21%2015.36.17.png?dl=0

Yes it is. Is the color contrast ratio good? I hope it is not too sparkly or shining. Also have you seen my comment regarding disabling scroll when no recipes found? Please implement that as well. :slightly_smiling_face: 

Thanks so much!

**Comment by NitinNair89** [comment]
Hi @PaulLiamAG - Waiting for your updates on this one :slightly_smiling_face:

**Comment by PaulLiamAG** [comment]
Hi, sorry for the delay.
I've been super busy with work. 
I will try to get to this asap, but if anyone else wants to take over the task that is fine also.

- Paul

**Comment by NitinNair89** [comment]
> Hi, sorry for the delay.
> I've been super busy with work.
> I will try to get to this asap, but if anyone else wants to take over the task that is fine also.
> 
> * Paul

No issues Paul. I think for now let me merge your changes. We can improve it later. Thank you so much for contributing! 👍

**Pull request merged**
