### PR TITLE
Fixes some recipes not being displayed

### PR DESCRIPTION
**Pull request by Jayashrri**
This fixes issue #1 .
The display problems were caused by quotes being present in the stringified JSON object, which caused the data-meal attribute to be set incorrectly.

Please let me know if there are any errors in this.

### CODE REVIEW

**Comment by NitinNair89** [comment]
> This fixes issue #1 .
> The display problems were caused by quotes being present in the stringified JSON object, which caused the data-meal attribute to be set incorrectly.
> 
> Please let me know if there are any errors in this.

Can you share a demo link where I can test it? You can add a Github page to your forked repo and share the link here. :slightly_smiling_face:

**Comment by NitinNair89** [comment]
Hi @Jayashrri - Please see my comment above :slightly_smiling_face:

**Comment by Jayashrri** [comment]
The link is https://jayashrri.github.io/TheHungryRecipes/

**Comment by NitinNair89** [comment]
> The link is https://jayashrri.github.io/TheHungryRecipes/

Well done. :slightly_smiling_face:

**Pull request merged**
