### PR TITLE
I added a change in <a>

### PR DESCRIPTION
**Pull request by Sriramrepaka**
I added this small change so than when you search for recipe using the input field and then click the random or latest then the input field is emptied.hope you like it
let me know for any other changes

### CODE REVIEW

**Review by NitinNair89 — CHANGES_REQUESTED** [review]
Can you open an issue first and describe the details? Also please handle JavaScript code in JS file and remove it from HTML.

**Comment by NitinNair89** [comment]
@Sriramrepaka Are you working on this?

**Comment by Sriramrepaka** [comment]
Yes for sure sry I was a bit busy

So yeah here is gist of what I did
So when you search for a recipe you input field has some value

So when you click the random recipe the input field is still full 

So I made a change by emptying the input after clicking the random recipe 

So can you please tell me why you reported this  PR

**Comment by Sriramrepaka** [comment]
Yes for sure sry I was a bit busy

So yeah here is gist of what I did
So when you search for a recipe you input field has some value

So when you click the random recipe the input field is still full 

So I made a change by emptying the input after clicking the random recipe 

So can you please tell me why you reported this  PR

**Comment by NitinNair89** [comment]
> Yes for sure sry I was a bit busy
> 
> So yeah here is gist of what I did
> So when you search for a recipe you input field has some value
> 
> So when you click the random recipe the input field is still full
> 
> So I made a change by emptying the input after clicking the random recipe
> 
> So can you please tell me why you reported this PR

Ok good. Please remove JavaScript within html and handle the code in app.js.

I thought you left the PR and did it only for hacktoberfest. :slightly_smiling_face:

**Comment by Sriramrepaka** [comment]
By tomorrow 17:30 I will make the changes and possibly add an fevicon also sry for the delay

**Comment by NitinNair89** [comment]
> By tomorrow 17:30 I will make the changes and possibly add an fevicon also sry for the delay

Sure. Please pull the latest code to your fork before you start working.

**Comment by Sriramrepaka** [comment]
OK sure

**Comment by NitinNair89** [comment]
> Removed the JS codes

Please pull latest code and resolve conflicts

**Comment by Sriramrepaka** [comment]
OK fine

**Review by NitinNair89 — APPROVED** [review]
Good to go. Thank you 😊

**Comment by Sriramrepaka** [comment]
My pleasure

**Pull request merged**
