### PR TITLE
Add Recipe Category Navbar

### PR DESCRIPTION
**Pull request by saguins**
- Add Recipe Category Navbar in index.html
- Add fetch method to get category list from MealDB by API
- Add fetchCategoryMeal function to create meal cards from category filter API

### CODE REVIEW

**Comment by saguins** [comment]
**Image Preview**

image

This is a result when I'm click **'Vegan'** from Recipe Category Navbar.

image

**Comment by NitinNair89** [comment]
Cool contribution! Can you align the categories to make it look better?

**Comment by saguins** [comment]
image

much better!

**Comment by NitinNair89** [comment]
> image
> 
> much better!

Hmm..looks better than before. But can you limit the width so that it stays within the boundaries of the input field? :)

**Comment by saguins** [comment]
image

Do you mean like this?

**Comment by NitinNair89** [comment]
> image
> 
> Do you mean like this?

No..it should be within the width of the input field. So categories will appear beneath the input field and will not extend outside that box view.

**Comment by NitinNair89** [comment]
@saguins - Please see below image for reference. Can you list the categories, limit to 2 or 3 lines and position it inside the red boundary?

Suggestion

**Comment by saguins** [comment]
image
Because numbers of categories is a lot. The best I can do is set a navbar format like what you said with a smaller size

**Comment by NitinNair89** [comment]
> image
> Because numbers of categories is a lot. The best I can do is set a navbar format like what you said with a smaller size

Ah okay. What about reducing font size and spacing between them? Keep the boundary and implement whatever you think would look the best. :)

**Comment by saguins** [comment]
image


Ohhhh I forgot that I can reducing space between list. **Thanks for your mention!**
I also reduce font size a little bit to make it look different from navbar at the top of a website.

**Full preview**

image

**Comment by NitinNair89** [comment]
Now it looks perfect. I like how it looks as an upside-down triangle due to center alignment. :)

@saguins please comment on issue number 13 so that I can assign it to you

**Comment by NitinNair89** [comment]
Closes #13

**Comment by NitinNair89** [comment]
@saguins  the meal categories doesn't look like what you showed in the image below. Anything missed?

**Pull request merged**
